#ifndef HWCONFIG_INCLUDED
#define HWCONFIG_INCLUDED

#define TEST_32KI_CLOCK_ACCURACY     (NRF_CLOCK_LFCLKSRC_XTAL_75_PPM)
#define TEST_DCDC_MODE               (NRF_POWER_DCDC_DISABLE)
#define TEST_16M_XTAL_MODE_AUTOMATIC
#define TEST_CPU_LOCK_MODE_ON        (0)

#endif // HWCONFIG_INCLUDED
